name: Render documentation
on: [ push ]


permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: arc42/documentation.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: ARC42 Documentation
          path: arc42_documentation.pdf
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Change
          branch: master
          commit_options: '--no-verify --signoff'
          commit_author: Author <actions@github.com>
          status_options: '--untracked-files=no'
          skip_dirty_check: true
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate and Deploy API Docs
        uses: msayson/openapi-github-pages-action@v2
        with:
          api-configs: '[{"openapi-yaml-filepath": "swagger/documentation.yaml", "api-doc-filepath": "index.html"}]'
          api-docs-dir: "docs"